# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cf_app.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cf_app.proto',
  package='cf.app',
  serialized_pb=_b('\n\x0c\x63\x66_app.proto\x12\x06\x63\x66.app\"@\n\x06Header\x12\x0e\n\x06sender\x18\x01 \x02(\t\x12\x13\n\x0bsender_type\x18\x02 \x02(\t\x12\x11\n\tinvoke_id\x18\x03 \x01(\r\"\xa5\x01\n\x07Message\x12\x1e\n\x06header\x18\x01 \x02(\x0b\x32\x0e.cf.app.Header\x12\x36\n\x10req_push_message\x18\n \x01(\x0b\x32\x1a.cf.app.PushMessageRequestH\x00\x12\x37\n\x10res_push_message\x18\x0b \x01(\x0b\x32\x1b.cf.app.PushMessageResponseH\x00\x42\t\n\x07\x63ontent\"\xc1\x01\n\x0eMessageContent\x12\x31\n\x04type\x18\x01 \x02(\x0e\x32#.cf.app.MessageContent.EMessageType\x12\x0f\n\x07\x63ontent\x18\x02 \x02(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12 \n\x06\x65xtras\x18\x04 \x03(\x0b\x32\x10.cf.app.KeyValue\":\n\x0c\x45MessageType\x12\x10\n\x0cNotification\x10\x01\x12\x0f\n\x0bInformation\x10\x02\x12\x07\n\x03\x41ll\x10\t\"\xe6\x01\n\x17\x43ustomerSearchCondition\x12\n\n\x02id\x18\n \x01(\t\x12\x15\n\rcf_account_id\x18\x0b \x01(\t\x12\x16\n\x0ewechat_open_id\x18\x0c \x01(\t\x12\x17\n\x0fwechat_union_id\x18\r \x01(\t\x12\x0c\n\x04\x63ode\x18\x12 \x01(\t\x12\x0e\n\x06\x61li_id\x18\x0e \x01(\t\x12\x0e\n\x06mobile\x18\x0f \x01(\t\x12\x12\n\ndevice_mac\x18\x10 \x01(\t\x12\r\n\x05\x65mail\x18\x11 \x01(\t\x12\x15\n\rapp_device_id\x18\x15 \x01(\t\x12\x0f\n\x07\x63\x61rd_id\x18\x16 \x01(\t\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\n \x02(\t\x12\r\n\x05value\x18\x14 \x01(\t\"\xc7\x01\n\x12PushMessageRequest\x12\x12\n\naccount_id\x18\n \x02(\t\x12(\n\x0b\x64\x65vice_type\x18\x14 \x03(\x0e\x32\x13.cf.app.EDeviceType\x12\x42\n\x19\x63ustomer_search_condition\x18( \x03(\x0b\x32\x1f.cf.app.CustomerSearchCondition\x12/\n\x0fmessage_content\x18\x46 \x02(\x0b\x32\x16.cf.app.MessageContent\"J\n\x13PushMessageResponse\x12\x0f\n\x07\x65rrcode\x18\x01 \x02(\x05\x12\x0e\n\x06\x65rrmsg\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\n \x01(\t*:\n\x0b\x45\x44\x65viceType\x12\x07\n\x03iOS\x10\x01\x12\x0b\n\x07\x41ndriod\x10\x02\x12\x0c\n\x08Winphone\x10\x03\x12\x07\n\x03\x41ll\x10\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_EDEVICETYPE = _descriptor.EnumDescriptor(
  name='EDeviceType',
  full_name='cf.app.EDeviceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='iOS', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Andriod', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Winphone', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='All', index=3, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=1005,
  serialized_end=1063,
)
_sym_db.RegisterEnumDescriptor(_EDEVICETYPE)

EDeviceType = enum_type_wrapper.EnumTypeWrapper(_EDEVICETYPE)
iOS = 1
Andriod = 2
Winphone = 3
All = 9


_MESSAGECONTENT_EMESSAGETYPE = _descriptor.EnumDescriptor(
  name='EMessageType',
  full_name='cf.app.MessageContent.EMessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Notification', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Information', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='All', index=2, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=394,
  serialized_end=452,
)
_sym_db.RegisterEnumDescriptor(_MESSAGECONTENT_EMESSAGETYPE)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='cf.app.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='cf.app.Header.sender', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sender_type', full_name='cf.app.Header.sender_type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='invoke_id', full_name='cf.app.Header.invoke_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=88,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='cf.app.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='cf.app.Message.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='req_push_message', full_name='cf.app.Message.req_push_message', index=1,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res_push_message', full_name='cf.app.Message.res_push_message', index=2,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='cf.app.Message.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=91,
  serialized_end=256,
)


_MESSAGECONTENT = _descriptor.Descriptor(
  name='MessageContent',
  full_name='cf.app.MessageContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='cf.app.MessageContent.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='cf.app.MessageContent.content', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='cf.app.MessageContent.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extras', full_name='cf.app.MessageContent.extras', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGECONTENT_EMESSAGETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=452,
)


_CUSTOMERSEARCHCONDITION = _descriptor.Descriptor(
  name='CustomerSearchCondition',
  full_name='cf.app.CustomerSearchCondition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cf.app.CustomerSearchCondition.id', index=0,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cf_account_id', full_name='cf.app.CustomerSearchCondition.cf_account_id', index=1,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wechat_open_id', full_name='cf.app.CustomerSearchCondition.wechat_open_id', index=2,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wechat_union_id', full_name='cf.app.CustomerSearchCondition.wechat_union_id', index=3,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='cf.app.CustomerSearchCondition.code', index=4,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ali_id', full_name='cf.app.CustomerSearchCondition.ali_id', index=5,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mobile', full_name='cf.app.CustomerSearchCondition.mobile', index=6,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_mac', full_name='cf.app.CustomerSearchCondition.device_mac', index=7,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='cf.app.CustomerSearchCondition.email', index=8,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_device_id', full_name='cf.app.CustomerSearchCondition.app_device_id', index=9,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='card_id', full_name='cf.app.CustomerSearchCondition.card_id', index=10,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=685,
)


_KEYVALUE = _descriptor.Descriptor(
  name='KeyValue',
  full_name='cf.app.KeyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cf.app.KeyValue.key', index=0,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='cf.app.KeyValue.value', index=1,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=687,
  serialized_end=725,
)


_PUSHMESSAGEREQUEST = _descriptor.Descriptor(
  name='PushMessageRequest',
  full_name='cf.app.PushMessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='cf.app.PushMessageRequest.account_id', index=0,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_type', full_name='cf.app.PushMessageRequest.device_type', index=1,
      number=20, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='customer_search_condition', full_name='cf.app.PushMessageRequest.customer_search_condition', index=2,
      number=40, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_content', full_name='cf.app.PushMessageRequest.message_content', index=3,
      number=70, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=728,
  serialized_end=927,
)


_PUSHMESSAGERESPONSE = _descriptor.Descriptor(
  name='PushMessageResponse',
  full_name='cf.app.PushMessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errcode', full_name='cf.app.PushMessageResponse.errcode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errmsg', full_name='cf.app.PushMessageResponse.errmsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='cf.app.PushMessageResponse.message_id', index=2,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=929,
  serialized_end=1003,
)

_MESSAGE.fields_by_name['header'].message_type = _HEADER
_MESSAGE.fields_by_name['req_push_message'].message_type = _PUSHMESSAGEREQUEST
_MESSAGE.fields_by_name['res_push_message'].message_type = _PUSHMESSAGERESPONSE
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['req_push_message'])
_MESSAGE.fields_by_name['req_push_message'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['res_push_message'])
_MESSAGE.fields_by_name['res_push_message'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGECONTENT.fields_by_name['type'].enum_type = _MESSAGECONTENT_EMESSAGETYPE
_MESSAGECONTENT.fields_by_name['extras'].message_type = _KEYVALUE
_MESSAGECONTENT_EMESSAGETYPE.containing_type = _MESSAGECONTENT
_PUSHMESSAGEREQUEST.fields_by_name['device_type'].enum_type = _EDEVICETYPE
_PUSHMESSAGEREQUEST.fields_by_name['customer_search_condition'].message_type = _CUSTOMERSEARCHCONDITION
_PUSHMESSAGEREQUEST.fields_by_name['message_content'].message_type = _MESSAGECONTENT
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['MessageContent'] = _MESSAGECONTENT
DESCRIPTOR.message_types_by_name['CustomerSearchCondition'] = _CUSTOMERSEARCHCONDITION
DESCRIPTOR.message_types_by_name['KeyValue'] = _KEYVALUE
DESCRIPTOR.message_types_by_name['PushMessageRequest'] = _PUSHMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['PushMessageResponse'] = _PUSHMESSAGERESPONSE
DESCRIPTOR.enum_types_by_name['EDeviceType'] = _EDEVICETYPE

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'cf_app_pb2'
  # @@protoc_insertion_point(class_scope:cf.app.Header)
  ))
_sym_db.RegisterMessage(Header)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'cf_app_pb2'
  # @@protoc_insertion_point(class_scope:cf.app.Message)
  ))
_sym_db.RegisterMessage(Message)

MessageContent = _reflection.GeneratedProtocolMessageType('MessageContent', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGECONTENT,
  __module__ = 'cf_app_pb2'
  # @@protoc_insertion_point(class_scope:cf.app.MessageContent)
  ))
_sym_db.RegisterMessage(MessageContent)

CustomerSearchCondition = _reflection.GeneratedProtocolMessageType('CustomerSearchCondition', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMERSEARCHCONDITION,
  __module__ = 'cf_app_pb2'
  # @@protoc_insertion_point(class_scope:cf.app.CustomerSearchCondition)
  ))
_sym_db.RegisterMessage(CustomerSearchCondition)

KeyValue = _reflection.GeneratedProtocolMessageType('KeyValue', (_message.Message,), dict(
  DESCRIPTOR = _KEYVALUE,
  __module__ = 'cf_app_pb2'
  # @@protoc_insertion_point(class_scope:cf.app.KeyValue)
  ))
_sym_db.RegisterMessage(KeyValue)

PushMessageRequest = _reflection.GeneratedProtocolMessageType('PushMessageRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUSHMESSAGEREQUEST,
  __module__ = 'cf_app_pb2'
  # @@protoc_insertion_point(class_scope:cf.app.PushMessageRequest)
  ))
_sym_db.RegisterMessage(PushMessageRequest)

PushMessageResponse = _reflection.GeneratedProtocolMessageType('PushMessageResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUSHMESSAGERESPONSE,
  __module__ = 'cf_app_pb2'
  # @@protoc_insertion_point(class_scope:cf.app.PushMessageResponse)
  ))
_sym_db.RegisterMessage(PushMessageResponse)


# @@protoc_insertion_point(module_scope)
