# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sr_customer_coupon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sr_customer_coupon.proto',
  package='sr.customer.coupon',
  serialized_pb=_b('\n\x18sr_customer_coupon.proto\x12\x12sr.customer.coupon\"@\n\x06Header\x12\x0e\n\x06sender\x18\x01 \x02(\t\x12\x13\n\x0bsender_type\x18\x02 \x02(\t\x12\x11\n\tinvoke_id\x18\x03 \x01(\r\"\xcf\x01\n\x07Message\x12*\n\x06header\x18\x01 \x02(\x0b\x32\x1a.sr.customer.coupon.Header\x12\x45\n\x11req_reward_coupon\x18\x14 \x01(\x0b\x32(.sr.customer.coupon.RewardsCouponRequestH\x00\x12\x46\n\x11res_reward_coupon\x18\x15 \x01(\x0b\x32).sr.customer.coupon.RewardsCouponResponseH\x00\x42\t\n\x07\x63ontent\"\xf9\x01\n\x14RewardsCouponRequest\x12\x10\n\x08\x63ouponid\x18\x01 \x02(\x05\x12\x0e\n\x06\x63ustid\x18\x02 \x02(\x05\x12\x14\n\x0c\x61\x63tivityname\x18\x03 \x02(\t\x12\x0f\n\x07tradeid\x18\x04 \x01(\x05\x12\x10\n\x08quantity\x18\x05 \x02(\x05\x12\x17\n\x0fsendchannelcode\x18\x06 \x02(\x05\x12\x19\n\x11\x64\x65tailchannelcode\x18\x07 \x01(\x05\x12\x1d\n\x15\x61pplicablechannelcode\x18\x08 \x02(\x05\x12\x14\n\x0cwechatcardid\x18\t \x01(\t\x12\x0e\n\x06remark\x18\n \x01(\t\x12\r\n\x05point\x18\x0b \x01(\x05\"8\n\x15RewardsCouponResponse\x12\x0f\n\x07\x65rrcode\x18\x01 \x02(\x05\x12\x0e\n\x06\x65rrmsg\x18\x02 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='sr.customer.coupon.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='sr.customer.coupon.Header.sender', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sender_type', full_name='sr.customer.coupon.Header.sender_type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='invoke_id', full_name='sr.customer.coupon.Header.invoke_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=112,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='sr.customer.coupon.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='sr.customer.coupon.Message.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='req_reward_coupon', full_name='sr.customer.coupon.Message.req_reward_coupon', index=1,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res_reward_coupon', full_name='sr.customer.coupon.Message.res_reward_coupon', index=2,
      number=21, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='sr.customer.coupon.Message.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=115,
  serialized_end=322,
)


_REWARDSCOUPONREQUEST = _descriptor.Descriptor(
  name='RewardsCouponRequest',
  full_name='sr.customer.coupon.RewardsCouponRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='couponid', full_name='sr.customer.coupon.RewardsCouponRequest.couponid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custid', full_name='sr.customer.coupon.RewardsCouponRequest.custid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activityname', full_name='sr.customer.coupon.RewardsCouponRequest.activityname', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tradeid', full_name='sr.customer.coupon.RewardsCouponRequest.tradeid', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='sr.customer.coupon.RewardsCouponRequest.quantity', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sendchannelcode', full_name='sr.customer.coupon.RewardsCouponRequest.sendchannelcode', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='detailchannelcode', full_name='sr.customer.coupon.RewardsCouponRequest.detailchannelcode', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='applicablechannelcode', full_name='sr.customer.coupon.RewardsCouponRequest.applicablechannelcode', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wechatcardid', full_name='sr.customer.coupon.RewardsCouponRequest.wechatcardid', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remark', full_name='sr.customer.coupon.RewardsCouponRequest.remark', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point', full_name='sr.customer.coupon.RewardsCouponRequest.point', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=574,
)


_REWARDSCOUPONRESPONSE = _descriptor.Descriptor(
  name='RewardsCouponResponse',
  full_name='sr.customer.coupon.RewardsCouponResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errcode', full_name='sr.customer.coupon.RewardsCouponResponse.errcode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errmsg', full_name='sr.customer.coupon.RewardsCouponResponse.errmsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=576,
  serialized_end=632,
)

_MESSAGE.fields_by_name['header'].message_type = _HEADER
_MESSAGE.fields_by_name['req_reward_coupon'].message_type = _REWARDSCOUPONREQUEST
_MESSAGE.fields_by_name['res_reward_coupon'].message_type = _REWARDSCOUPONRESPONSE
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['req_reward_coupon'])
_MESSAGE.fields_by_name['req_reward_coupon'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['res_reward_coupon'])
_MESSAGE.fields_by_name['res_reward_coupon'].containing_oneof = _MESSAGE.oneofs_by_name['content']
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['RewardsCouponRequest'] = _REWARDSCOUPONREQUEST
DESCRIPTOR.message_types_by_name['RewardsCouponResponse'] = _REWARDSCOUPONRESPONSE

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'sr_customer_coupon_pb2'
  # @@protoc_insertion_point(class_scope:sr.customer.coupon.Header)
  ))
_sym_db.RegisterMessage(Header)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'sr_customer_coupon_pb2'
  # @@protoc_insertion_point(class_scope:sr.customer.coupon.Message)
  ))
_sym_db.RegisterMessage(Message)

RewardsCouponRequest = _reflection.GeneratedProtocolMessageType('RewardsCouponRequest', (_message.Message,), dict(
  DESCRIPTOR = _REWARDSCOUPONREQUEST,
  __module__ = 'sr_customer_coupon_pb2'
  # @@protoc_insertion_point(class_scope:sr.customer.coupon.RewardsCouponRequest)
  ))
_sym_db.RegisterMessage(RewardsCouponRequest)

RewardsCouponResponse = _reflection.GeneratedProtocolMessageType('RewardsCouponResponse', (_message.Message,), dict(
  DESCRIPTOR = _REWARDSCOUPONRESPONSE,
  __module__ = 'sr_customer_coupon_pb2'
  # @@protoc_insertion_point(class_scope:sr.customer.coupon.RewardsCouponResponse)
  ))
_sym_db.RegisterMessage(RewardsCouponResponse)


# @@protoc_insertion_point(module_scope)
