# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sr_job_task.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sr_job_task.proto',
  package='sr.job.task',
  serialized_pb=_b('\n\x11sr_job_task.proto\x12\x0bsr.job.task\"@\n\x06Header\x12\x0e\n\x06sender\x18\x01 \x02(\t\x12\x13\n\x0bsender_type\x18\x02 \x02(\t\x12\x11\n\tinvoke_id\x18\x03 \x01(\r\"\xd5\x03\n\x07Message\x12#\n\x06header\x18\x01 \x02(\x0b\x32\x13.sr.job.task.Header\x12\x33\n\x0creq_task_run\x18\x02 \x01(\x0b\x32\x1b.sr.job.task.RunTaskRequestH\x00\x12\x34\n\x0cres_task_run\x18\x03 \x01(\x0b\x32\x1c.sr.job.task.RunTaskResponseH\x00\x12\x39\n\x0freq_task_change\x18\x04 \x01(\x0b\x32\x1e.sr.job.task.ChangeTaskRequestH\x00\x12:\n\x0fres_task_change\x18\x05 \x01(\x0b\x32\x1f.sr.job.task.ChangeTaskResponseH\x00\x12=\n\x11req_session_close\x18\x06 \x01(\x0b\x32 .sr.job.task.SessionCloseRequestH\x00\x12;\n\x0ereq_tag_update\x18\x07 \x01(\x0b\x32!.sr.job.task.TagNameUpdateRequestH\x00\x12<\n\x0eres_tag_update\x18\x08 \x01(\x0b\x32\".sr.job.task.TagNameUpdateResponseH\x00\x42\t\n\x07\x63ontent\"\x1c\n\x0eRunTaskRequest\x12\n\n\x02id\x18\x01 \x02(\x05\"2\n\x0fRunTaskResponse\x12\x0f\n\x07\x65rrcode\x18\x01 \x02(\x05\x12\x0e\n\x06\x65rrmsg\x18\x02 \x01(\t\"3\n\x11\x43hangeTaskRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x12\n\nstatuscode\x18\x02 \x02(\x05\"5\n\x12\x43hangeTaskResponse\x12\x0f\n\x07\x65rrcode\x18\x01 \x02(\x05\x12\x0e\n\x06\x65rrmsg\x18\x02 \x01(\t\"F\n\x13SessionCloseRequest\x12\x0e\n\x06openid\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\x05\x12\x11\n\taccountid\x18\x03 \x02(\t\"3\n\x14TagNameUpdateRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0f\n\x07tagname\x18\x02 \x02(\t\"8\n\x15TagNameUpdateResponse\x12\x0f\n\x07\x65rrcode\x18\x01 \x02(\x05\x12\x0e\n\x06\x65rrmsg\x18\x02 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='sr.job.task.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='sr.job.task.Header.sender', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sender_type', full_name='sr.job.task.Header.sender_type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='invoke_id', full_name='sr.job.task.Header.invoke_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=98,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='sr.job.task.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='sr.job.task.Message.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='req_task_run', full_name='sr.job.task.Message.req_task_run', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res_task_run', full_name='sr.job.task.Message.res_task_run', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='req_task_change', full_name='sr.job.task.Message.req_task_change', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res_task_change', full_name='sr.job.task.Message.res_task_change', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='req_session_close', full_name='sr.job.task.Message.req_session_close', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='req_tag_update', full_name='sr.job.task.Message.req_tag_update', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res_tag_update', full_name='sr.job.task.Message.res_tag_update', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='sr.job.task.Message.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=101,
  serialized_end=570,
)


_RUNTASKREQUEST = _descriptor.Descriptor(
  name='RunTaskRequest',
  full_name='sr.job.task.RunTaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sr.job.task.RunTaskRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=572,
  serialized_end=600,
)


_RUNTASKRESPONSE = _descriptor.Descriptor(
  name='RunTaskResponse',
  full_name='sr.job.task.RunTaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errcode', full_name='sr.job.task.RunTaskResponse.errcode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errmsg', full_name='sr.job.task.RunTaskResponse.errmsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=602,
  serialized_end=652,
)


_CHANGETASKREQUEST = _descriptor.Descriptor(
  name='ChangeTaskRequest',
  full_name='sr.job.task.ChangeTaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sr.job.task.ChangeTaskRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='statuscode', full_name='sr.job.task.ChangeTaskRequest.statuscode', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=654,
  serialized_end=705,
)


_CHANGETASKRESPONSE = _descriptor.Descriptor(
  name='ChangeTaskResponse',
  full_name='sr.job.task.ChangeTaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errcode', full_name='sr.job.task.ChangeTaskResponse.errcode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errmsg', full_name='sr.job.task.ChangeTaskResponse.errmsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=707,
  serialized_end=760,
)


_SESSIONCLOSEREQUEST = _descriptor.Descriptor(
  name='SessionCloseRequest',
  full_name='sr.job.task.SessionCloseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='openid', full_name='sr.job.task.SessionCloseRequest.openid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='sr.job.task.SessionCloseRequest.type', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accountid', full_name='sr.job.task.SessionCloseRequest.accountid', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=762,
  serialized_end=832,
)


_TAGNAMEUPDATEREQUEST = _descriptor.Descriptor(
  name='TagNameUpdateRequest',
  full_name='sr.job.task.TagNameUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sr.job.task.TagNameUpdateRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tagname', full_name='sr.job.task.TagNameUpdateRequest.tagname', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=834,
  serialized_end=885,
)


_TAGNAMEUPDATERESPONSE = _descriptor.Descriptor(
  name='TagNameUpdateResponse',
  full_name='sr.job.task.TagNameUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errcode', full_name='sr.job.task.TagNameUpdateResponse.errcode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errmsg', full_name='sr.job.task.TagNameUpdateResponse.errmsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=887,
  serialized_end=943,
)

_MESSAGE.fields_by_name['header'].message_type = _HEADER
_MESSAGE.fields_by_name['req_task_run'].message_type = _RUNTASKREQUEST
_MESSAGE.fields_by_name['res_task_run'].message_type = _RUNTASKRESPONSE
_MESSAGE.fields_by_name['req_task_change'].message_type = _CHANGETASKREQUEST
_MESSAGE.fields_by_name['res_task_change'].message_type = _CHANGETASKRESPONSE
_MESSAGE.fields_by_name['req_session_close'].message_type = _SESSIONCLOSEREQUEST
_MESSAGE.fields_by_name['req_tag_update'].message_type = _TAGNAMEUPDATEREQUEST
_MESSAGE.fields_by_name['res_tag_update'].message_type = _TAGNAMEUPDATERESPONSE
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['req_task_run'])
_MESSAGE.fields_by_name['req_task_run'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['res_task_run'])
_MESSAGE.fields_by_name['res_task_run'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['req_task_change'])
_MESSAGE.fields_by_name['req_task_change'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['res_task_change'])
_MESSAGE.fields_by_name['res_task_change'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['req_session_close'])
_MESSAGE.fields_by_name['req_session_close'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['req_tag_update'])
_MESSAGE.fields_by_name['req_tag_update'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['res_tag_update'])
_MESSAGE.fields_by_name['res_tag_update'].containing_oneof = _MESSAGE.oneofs_by_name['content']
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['RunTaskRequest'] = _RUNTASKREQUEST
DESCRIPTOR.message_types_by_name['RunTaskResponse'] = _RUNTASKRESPONSE
DESCRIPTOR.message_types_by_name['ChangeTaskRequest'] = _CHANGETASKREQUEST
DESCRIPTOR.message_types_by_name['ChangeTaskResponse'] = _CHANGETASKRESPONSE
DESCRIPTOR.message_types_by_name['SessionCloseRequest'] = _SESSIONCLOSEREQUEST
DESCRIPTOR.message_types_by_name['TagNameUpdateRequest'] = _TAGNAMEUPDATEREQUEST
DESCRIPTOR.message_types_by_name['TagNameUpdateResponse'] = _TAGNAMEUPDATERESPONSE

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'sr_job_task_pb2'
  # @@protoc_insertion_point(class_scope:sr.job.task.Header)
  ))
_sym_db.RegisterMessage(Header)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'sr_job_task_pb2'
  # @@protoc_insertion_point(class_scope:sr.job.task.Message)
  ))
_sym_db.RegisterMessage(Message)

RunTaskRequest = _reflection.GeneratedProtocolMessageType('RunTaskRequest', (_message.Message,), dict(
  DESCRIPTOR = _RUNTASKREQUEST,
  __module__ = 'sr_job_task_pb2'
  # @@protoc_insertion_point(class_scope:sr.job.task.RunTaskRequest)
  ))
_sym_db.RegisterMessage(RunTaskRequest)

RunTaskResponse = _reflection.GeneratedProtocolMessageType('RunTaskResponse', (_message.Message,), dict(
  DESCRIPTOR = _RUNTASKRESPONSE,
  __module__ = 'sr_job_task_pb2'
  # @@protoc_insertion_point(class_scope:sr.job.task.RunTaskResponse)
  ))
_sym_db.RegisterMessage(RunTaskResponse)

ChangeTaskRequest = _reflection.GeneratedProtocolMessageType('ChangeTaskRequest', (_message.Message,), dict(
  DESCRIPTOR = _CHANGETASKREQUEST,
  __module__ = 'sr_job_task_pb2'
  # @@protoc_insertion_point(class_scope:sr.job.task.ChangeTaskRequest)
  ))
_sym_db.RegisterMessage(ChangeTaskRequest)

ChangeTaskResponse = _reflection.GeneratedProtocolMessageType('ChangeTaskResponse', (_message.Message,), dict(
  DESCRIPTOR = _CHANGETASKRESPONSE,
  __module__ = 'sr_job_task_pb2'
  # @@protoc_insertion_point(class_scope:sr.job.task.ChangeTaskResponse)
  ))
_sym_db.RegisterMessage(ChangeTaskResponse)

SessionCloseRequest = _reflection.GeneratedProtocolMessageType('SessionCloseRequest', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONCLOSEREQUEST,
  __module__ = 'sr_job_task_pb2'
  # @@protoc_insertion_point(class_scope:sr.job.task.SessionCloseRequest)
  ))
_sym_db.RegisterMessage(SessionCloseRequest)

TagNameUpdateRequest = _reflection.GeneratedProtocolMessageType('TagNameUpdateRequest', (_message.Message,), dict(
  DESCRIPTOR = _TAGNAMEUPDATEREQUEST,
  __module__ = 'sr_job_task_pb2'
  # @@protoc_insertion_point(class_scope:sr.job.task.TagNameUpdateRequest)
  ))
_sym_db.RegisterMessage(TagNameUpdateRequest)

TagNameUpdateResponse = _reflection.GeneratedProtocolMessageType('TagNameUpdateResponse', (_message.Message,), dict(
  DESCRIPTOR = _TAGNAMEUPDATERESPONSE,
  __module__ = 'sr_job_task_pb2'
  # @@protoc_insertion_point(class_scope:sr.job.task.TagNameUpdateResponse)
  ))
_sym_db.RegisterMessage(TagNameUpdateResponse)


# @@protoc_insertion_point(module_scope)
