# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sr_point.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sr_point.proto',
  package='sr.point',
  serialized_pb=_b('\n\x0esr_point.proto\x12\x08sr.point\"@\n\x06Header\x12\x0e\n\x06sender\x18\x01 \x02(\t\x12\x13\n\x0bsender_type\x18\x02 \x02(\t\x12\x11\n\tinvoke_id\x18\x03 \x01(\r\"\xaf\x01\n\x07Message\x12 \n\x06header\x18\x01 \x02(\x0b\x32\x10.sr.point.Header\x12:\n\x11req_receipt_point\x18\n \x01(\x0b\x32\x1d.sr.point.ReceiptPointRequestH\x00\x12;\n\x11res_receipt_point\x18\x0b \x01(\x0b\x32\x1e.sr.point.ReceiptPointResponseH\x00\x42\t\n\x07\x63ontent\"\xf0\x01\n\x13ReceiptPointRequest\x12\x10\n\x08\x61\x64\x64\x65\x64num\x18\x02 \x02(\x05\x12\x0e\n\x06\x63ustid\x18\x03 \x02(\x05\x12\x14\n\x0c\x61vailablenum\x18\x04 \x01(\x05\x12\x0f\n\x07gettime\x18\x05 \x01(\t\x12\x0f\n\x07\x64uetime\x18\x06 \x01(\t\x12\x13\n\x0b\x63hannelcode\x18\x07 \x01(\x05\x12\x10\n\x08sourceid\x18\x08 \x01(\x05\x12\x12\n\nstatuscode\x18\t \x01(\x05\x12\x0e\n\x06typeid\x18\n \x02(\x05\x12\x0e\n\x06remark\x18\x0b \x01(\t\x12\x0f\n\x07tradeid\x18\x0c \x01(\x05\x12\x13\n\x0btradeamount\x18\r \x01(\x01\"C\n\x14ReceiptPointResponse\x12\x0f\n\x07\x65rrcode\x18\x01 \x02(\x05\x12\x0e\n\x06\x65rrmsg\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='sr.point.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='sr.point.Header.sender', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sender_type', full_name='sr.point.Header.sender_type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='invoke_id', full_name='sr.point.Header.invoke_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=92,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='sr.point.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='sr.point.Message.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='req_receipt_point', full_name='sr.point.Message.req_receipt_point', index=1,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res_receipt_point', full_name='sr.point.Message.res_receipt_point', index=2,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='sr.point.Message.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=95,
  serialized_end=270,
)


_RECEIPTPOINTREQUEST = _descriptor.Descriptor(
  name='ReceiptPointRequest',
  full_name='sr.point.ReceiptPointRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addednum', full_name='sr.point.ReceiptPointRequest.addednum', index=0,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custid', full_name='sr.point.ReceiptPointRequest.custid', index=1,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='availablenum', full_name='sr.point.ReceiptPointRequest.availablenum', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gettime', full_name='sr.point.ReceiptPointRequest.gettime', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duetime', full_name='sr.point.ReceiptPointRequest.duetime', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channelcode', full_name='sr.point.ReceiptPointRequest.channelcode', index=5,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sourceid', full_name='sr.point.ReceiptPointRequest.sourceid', index=6,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='statuscode', full_name='sr.point.ReceiptPointRequest.statuscode', index=7,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='typeid', full_name='sr.point.ReceiptPointRequest.typeid', index=8,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remark', full_name='sr.point.ReceiptPointRequest.remark', index=9,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tradeid', full_name='sr.point.ReceiptPointRequest.tradeid', index=10,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tradeamount', full_name='sr.point.ReceiptPointRequest.tradeamount', index=11,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=513,
)


_RECEIPTPOINTRESPONSE = _descriptor.Descriptor(
  name='ReceiptPointResponse',
  full_name='sr.point.ReceiptPointResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errcode', full_name='sr.point.ReceiptPointResponse.errcode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errmsg', full_name='sr.point.ReceiptPointResponse.errmsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='sr.point.ReceiptPointResponse.id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=582,
)

_MESSAGE.fields_by_name['header'].message_type = _HEADER
_MESSAGE.fields_by_name['req_receipt_point'].message_type = _RECEIPTPOINTREQUEST
_MESSAGE.fields_by_name['res_receipt_point'].message_type = _RECEIPTPOINTRESPONSE
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['req_receipt_point'])
_MESSAGE.fields_by_name['req_receipt_point'].containing_oneof = _MESSAGE.oneofs_by_name['content']
_MESSAGE.oneofs_by_name['content'].fields.append(
  _MESSAGE.fields_by_name['res_receipt_point'])
_MESSAGE.fields_by_name['res_receipt_point'].containing_oneof = _MESSAGE.oneofs_by_name['content']
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['ReceiptPointRequest'] = _RECEIPTPOINTREQUEST
DESCRIPTOR.message_types_by_name['ReceiptPointResponse'] = _RECEIPTPOINTRESPONSE

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'sr_point_pb2'
  # @@protoc_insertion_point(class_scope:sr.point.Header)
  ))
_sym_db.RegisterMessage(Header)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'sr_point_pb2'
  # @@protoc_insertion_point(class_scope:sr.point.Message)
  ))
_sym_db.RegisterMessage(Message)

ReceiptPointRequest = _reflection.GeneratedProtocolMessageType('ReceiptPointRequest', (_message.Message,), dict(
  DESCRIPTOR = _RECEIPTPOINTREQUEST,
  __module__ = 'sr_point_pb2'
  # @@protoc_insertion_point(class_scope:sr.point.ReceiptPointRequest)
  ))
_sym_db.RegisterMessage(ReceiptPointRequest)

ReceiptPointResponse = _reflection.GeneratedProtocolMessageType('ReceiptPointResponse', (_message.Message,), dict(
  DESCRIPTOR = _RECEIPTPOINTRESPONSE,
  __module__ = 'sr_point_pb2'
  # @@protoc_insertion_point(class_scope:sr.point.ReceiptPointResponse)
  ))
_sym_db.RegisterMessage(ReceiptPointResponse)


# @@protoc_insertion_point(module_scope)
